# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b68fa4b5d47057edc096a03cfab57cd6eb471ff9cc838fee387991f853a3255f9f19bf4fbf270e52249fd78b03cf5753ef005309f03f0ff5c80b3e24f30b25a3

test:
  secret_key_base: a66122d436968359f19e4dd82ca3bcf435ac41dd723e76ea6a1994f6e114b6b0494c7a296c266db054a8b3114ec15640dcc537ccc8fa900454286cae7afc5b71

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
